name: Claude PR Action

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude-pr:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Anthropic SDK
        run: |
          pip install anthropic requests
          
      - name: Get Repository Contents
        run: |
          find . -name "*.js" -o -name "*.ts" -o -name "*.json" -o -name "*.md" -o -name "*.py" | head -20 > repo_files.txt
          echo "Repository structure:" > repo_analysis.txt
          ls -la >> repo_analysis.txt
          echo -e "\n\nKey files found:" >> repo_analysis.txt
          cat repo_files.txt >> repo_analysis.txt

      - name: Run Claude Analysis
        run: python claude_analyze.py
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ github.event.comment.body || github.event.issue.body }}
          ISSUE_URL: ${{ github.event.issue.comments_url || format('{0}/comments', github.event.issue.url) }}